### ISSUE TITLE
`execute.if.block` and `execute.unless.block` do not accept `Tag<'blocks'>`

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#161] opened 2022-01-20 10:33 UTC
![image](https://user-images.githubusercontent.com/14056899/150322017-898f7641-3cd9-4196-a632-a26590f7af5d.png)

**Comment by MulverineX** [comment] 2023-01-30 00:53
Duplicate of #172

**Closed by MulverineX** 2023-01-30 00:53 UTC
