### ISSUE TITLE
`execute.if.score` and `execute.unless.score` do not accept `Score`s directly

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#155] opened 2022-01-06 09:54 UTC
![image](https://user-images.githubusercontent.com/14056899/148364470-865df009-2566-4a10-a62c-48d3d2adb1eb.png)

**Comment by MulverineX** [comment] 2023-01-30 00:55
Duplicate of #172

**Closed by MulverineX** 2023-01-30 00:55 UTC

**Comment by GrantGryczan** [comment] 2023-02-01 01:49
Do note that it might be relatively complicated compared to the other duplicates of #172 to generalize this, since `Score`s are one argument while their primitive counterparts are two.

**Comment by MulverineX** [comment] 2023-02-01 01:51
It's already done ;D
