### ISSUE TITLE
`recipe_unlocked` advancement trigger does not accept recipes

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#140] opened 2021-12-27 03:26 UTC
![image](https://user-images.githubusercontent.com/14056899/147431382-8b4dcf41-2696-4e18-9ca3-6b37512f538a.png)

**Comment by MulverineX** [comment] 2023-01-30 01:07
Duplicate of #172

**Closed by MulverineX** 2023-01-30 01:07 UTC
