### ISSUE TITLE
`execute.if.predicate` doesn't accept `Predicate`s

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#171] opened 2022-03-10 01:46 UTC
![image](https://user-images.githubusercontent.com/14056899/157570908-3a87d382-cbf0-42a0-9217-ba0c506ad2a4.png)

**Comment by MulverineX** [comment] 2023-01-30 00:46
Duplicate of #172

**Closed by MulverineX** 2023-01-30 00:46 UTC
