### ISSUE TITLE
`tag.add` only accepts one argument and doesn't accept `Tag`

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#110] opened 2021-12-09 06:00 UTC
![image](https://user-images.githubusercontent.com/14056899/145342775-1555e455-d03d-4b3a-ac56-753c9b027052.png)

![image](https://user-images.githubusercontent.com/14056899/145361376-338d9bc9-3aaa-4ea3-8b3f-4ea50f5b9201.png)

![image](https://user-images.githubusercontent.com/14056899/146120159-4a5de7a2-850a-420b-be8b-a20f3ee07404.png)

**Comment by MulverineX** [comment] 2023-01-30 01:00
Duplicate of #153

**Closed by MulverineX** 2023-01-30 01:00 UTC
