### ISSUE TITLE
`tag.values` doesn't accept the type that the tag is of

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#146] opened 2021-12-27 11:07 UTC
For example, `mcFunctionTag.values` does not include `MCFunctionInstance` in its element type, even though it works fine in JS runtime.

![image](https://user-images.githubusercontent.com/14056899/147465914-169614bb-3a3b-49d7-8658-b61a6b4522af.png)

**Comment by MulverineX** [comment] 2023-01-30 01:02
Duplicate of #172

**Closed by MulverineX** 2023-01-30 01:02 UTC
