### ISSUE TITLE
Predicate reference `name`s don't accept `Predicate`s

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#151] opened 2022-01-03 02:53 UTC
![image](https://user-images.githubusercontent.com/14056899/147895914-7126fb57-d11c-4ffa-9e66-e579df519b05.png)

**Comment by MulverineX** [comment] 2023-01-30 00:58
Duplicate of #172

**Closed** 2023-01-30 01:20 UTC
