### ISSUE TITLE
Advancement loot table rewards don't accept loot tables

### ISSUE THREAD

**Issue by GrantGryczan** [sandstone-mc/sandstone#139] opened 2021-12-27 03:22 UTC
![image](https://user-images.githubusercontent.com/14056899/147431098-12e86bc4-d0af-47c7-8284-f4cc0e4b6b71.png)

**Comment by MulverineX** [comment] 2023-01-30 01:07
Duplicate of #172

**Closed by MulverineX** 2023-01-30 01:07 UTC
