### ISSUE TITLE
JSON Text Components with Selector syntax

### ISSUE THREAD

**Issue by ColinTimBarndt** [sandstone-mc/sandstone#98] opened 2021-08-29 22:53 UTC
The following example does not compile because the selector only accepts strings. It would be nice to be able to use selectors in JSON Text Components without appending `.toString()`. This is already implemented for score components.
```ts
import { Selector, MCFunction, tellraw } from 'sandstone'

MCFunction('hello', () => {
  const closest = Selector('@p', {distance: [.1, Infinity]})

  tellraw(Selector('@a'), {
    text: 'My closest friend is ',
    extra: [
      { selector: closest }
    ]
  })
})
```

**Comment by ColinTimBarndt** [comment] 2021-08-29 23:23
Also, the selector component is missing the optional "separator" property, which is very useful.

Reference: https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Entity_Names

**Comment by MulverineX** [comment] 2023-01-30 01:18
Duplicate of #172

**Closed by MulverineX** 2023-01-30 01:18 UTC
